

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UserRegisteration.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UserRegisterationEntities : DbContext
{
    public UserRegisterationEntities()
        : base("name=UserRegisterationEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<postnr> postnrs { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

